<a href="https://colab.research.google.com/github/jhashekhar/np-imp/blob/master/attention_mechanism_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [9]:
# vector of embeddings
# let's say the number of the tokens/words or for the sake of simplicity the length of sentence is V = 3
# with each V_i (embedding) be of size (1 x 2)
# so [1, 6, 10]

torch.Tensor([[0.2, 0.3], [0.3, 0.4], [0.7, 0.5]]).unsqueeze(0).shape

torch.Size([1, 3, 2])

In [30]:
torch.manual_seed(33)
q = torch.randn(1, 3, 2)
k = torch.randn(1, 3, 2)
print(q, '\n\n' , k)

tensor([[[ 1.1982, -0.3998],
         [-0.3476, -0.2759],
         [-2.3094, -1.0931]]]) 

 tensor([[[-0.0808,  0.7721],
         [-1.1370, -0.4773],
         [-1.0679,  1.0688]]])


In [0]:
q, k = q.reshape(1, -1), k.view(1, -1)

In [36]:
print(q.size(), k.size())
q.view(-1, 1).size()

torch.Size([1, 6]) torch.Size([1, 6])


torch.Size([6, 1])

In [38]:
torch.matmul(q.view(-1, 1), k)

tensor([[-0.0968,  0.9251, -1.3624, -0.5718, -1.2796,  1.2806],
        [ 0.0323, -0.3087,  0.4546,  0.1908,  0.4270, -0.4273],
        [ 0.0281, -0.2684,  0.3953,  0.1659,  0.3712, -0.3715],
        [ 0.0223, -0.2130,  0.3137,  0.1317,  0.2946, -0.2948],
        [ 0.1866, -1.7830,  2.6259,  1.1022,  2.4662, -2.4682],
        [ 0.0883, -0.8440,  1.2430,  0.5217,  1.1674, -1.1683]])

In [43]:
# Softmax(similarity_measure)
softmax = torch.nn.Softmax(dim=0)
softmax(torch.matmul(q.view(-1, 1), k))

tensor([[0.1443, 0.4647, 0.0117, 0.0642, 0.0142, 0.5918],
        [0.1642, 0.1353, 0.0717, 0.1377, 0.0782, 0.1073],
        [0.1635, 0.1409, 0.0676, 0.1343, 0.0740, 0.1134],
        [0.1626, 0.1489, 0.0623, 0.1298, 0.0685, 0.1225],
        [0.1916, 0.0310, 0.6290, 0.3425, 0.6011, 0.0139],
        [0.1737, 0.0792, 0.1578, 0.1917, 0.1640, 0.0511]])